version: '2.0'

services:

    nginx:
#        image: nginx:latest
        build: ./nginx
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/confs:/etc/nginx/conf.d
            - ./app/:/var/www/
            - ./nginx/logs:/var/log/nginx
        links:
            - php

    mysql:
        build: ./mysql
#        image: mysql:5.7
        ports:
            - "3306:3306"
        container_name: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=1111
            - MYSQL_DATABASE=db
            - MYSQL_USER=dbuser
            - MYSQL_PASSWORD=1111
        volumes:
            - ./mysql/workdir:/var/lib/mysql

    php:
        build: ./php
        container_name: php-fpm
        volumes:
            - ./app/:/var/www/
        links:
            - mysql

