FROM nginx

#ADD core/nginx.conf /etc/nginx/conf.d/
#RUN mkdir -p /var/www/seotoaster
#ADD seotoaster /var/www/seotoaster
#RUN rm -rf /var/www/seotoaster/cache/zend-cache*
#RUN chown -R www-data:www-data /var/www/seotoaster
